check my changes.
Pranav016/Hacktoberfest-PR-for-beginners pull request #70
Opened 2021-10-04 16:02 UTC by Anweshapal

2021-10-05 18:03 UTC, Pranav016 requested changes

2021-10-05 18:03 UTC, Pranav016 commented on C codes/CapitalorSmall.c
> +	if(ch >= 65 && ch <= 90)// range will strats from 65 not 67
correct spelling mistake in this line `start`

2021-10-06 16:16 UTC, Anweshapal commented on C codes/CapitalorSmall.c
> +	if(ch >= 65 && ch <= 90)// range will strats from 65 not 67
done

2021-10-06 16:17 UTC, Anweshapal reviewed
done

2021-10-07 17:24 UTC, merged